language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8.11.3
install:
  - npm install -g npm@6.1.0
  - npm install
script:
  - npm run test
deploy:
  - provider: npm
    email: sageoneplatform@sage.com
    api_key:
      secure: "x/qTKecxkGNNqDR/J2xCdzb1HccKSNZyFOB2sbAzMA3UfxiB0s5unDZ3MT6mRnfbm93Rj4CfPkQ5KRiIqbaWOKpthLGPCKrgV8QQPZAXbkxNDyse2ssBj8m1wNODTx4VXQ7z16TYR1cGIcdkNgjzR+snUEFuxl6YcPZsgcL2+gWL+f/oPeJ2J9ruLgMi7OonuTa1rwxz5tr2ypyzaURo+4VZBq5kOIWYAyW5ICTNXsFcgeFSixCXIqbZLotagiHlCHFqeXFKf1qY3THrFs7IA+VtoRAcZ04QqcwgU03L46Bvsv54PWdXqQ+EbSVL7H9fn2Xa5ShAJBSMrhK4hozJhAJZKLTt9OaRf1qXnc3SpusoxxaQVeGdL8Qo4vNwyQMor73wDsffWx+anV8Tw0wuBzlNjNi2JV7PJP/MqS0Ph3R/kjMl4+9OWmU9Mh1t123tae/r++ghZc/ZE+O7e+21Gg2atzhPGMCyDfa1+b2gXpfAXipgv5lJU1drx5gIrXd94SmKYy1s8XVMSSpD0ybRgCZIXPzn69wB1dPe2ELOgJB2IhSm63DdT7OD7awyedmvz0w5wnAMA8gLlEFlN/wWM5KNQV39aZk8tutobYFRt7pnyFvy88fH6FOf8C4R1w0eUbocFHnXEcTCe8gRnuzoq7RSnf3V6BrDwwXR2YyBoZI="
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^((v[0-9]+.[0-9]+.[0-9]+)(-rc[0-9]+)?)$"
