language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8.11.3
install:
  - npm install -g npm@6.1.0
  - npm install
script:
  - npm run test
deploy:
  - provider: npm
    email: sageoneplatform@sage.com
    api_key:
      secure: jV4duI6Wa6HIawPIv/t/wSJJkkOJoPNgBg8P7InjNN9xaUeBYGWaVHbfuZQiCnf/DzQFjEjklg43cCzj7Hc7oirTfaLxuGBKkmNf4jKcnrwptzXRJCsSw8snMgtrkmiDYs36YlrxoBc9W6cXwMBqlevEuaDxvn4Hy/tILjCtIcYu7MmP0eDTCs7BM95cfikQJYbPSOX4h98n/tFFphmKTFbEaSNXO/+INp5n6u0lTwBDSzjSh5VnvW+CM+QsnbzIkxhZpPqInKeZaaRUeVcDNSrGRfr1CHCNOiZomgtS840jR7cSYZZllPTgNDWbxXlzVeRJy8ylXLbmuE/3FG7CLQrwoiGQ0at/SiaqdxbD8Czx53TPQ9G9opCh85pTb2XZAf70cQs3twbV2UESlBYxuZrpBIyVhtq60AAAWQ341pbBRfQwBB6dwP81MnIjHiK/RWGuTzYkpTmJCg5VXkptIy2HrxsSDpVbz11OIPRRRcB2oD+T6gWaadrXqan+yPZR6ajTVFfJhQjis4bskRtSCy6a2To41d3c3d2EMVeA0MmrQhH3FeOOWgVITr6fwerTfTYw+DdhrlEmRBn/5hxSAcmIgC0+hPlU0MTdQf3QcC4aPJ2IqRzJRiRbX0BSzIpab4w/Y9yBY2R++00Rao2GkH0t4rD/Wf2D5eUv3q4qkGA=
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^((v[0-9]+.[0-9]+.[0-9]+)(-rc[0-9]+)?)$"
