language: node_js

cache:
  directories:
    - node_modules

node_js:
  - 8.11.3

install:
  - npm install -g npm@6.1.0
  - npm install

script:
  - npm run test

before_deploy: if [ "$TRAVIS_BRANCH" == "release" ]; then npm run build; fi